trigger:
- none

resources:
- repo: self

pool:
  vmImage: 'ubuntu-latest'

variables:
  branchName: $[replace(variables['Build.SourceBranchName'], 'refs/heads/', '')]

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.13.0'
  displayName: 'Install Node.js 18.13.0'

- script: |
    npm install --force
    npm audit fix
    npm run build
  displayName: 'npm install and build'
  workingDirectory: '$(Build.SourcesDirectory)'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/dist/delphi-ai-library-ui' 
    contents: '**/*'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)' 
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    includeRootFolder: false
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'
